name: Packer Build

on:
  workflow_dispatch:  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup HashiCorp Packer
      uses: hashicorp/setup-packer@v2.0.1

    - name: Fetch ConfD
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.DO_SPACES_DEV_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.DO_SPACES_DEV_ACCESS_KEY }}
      run: |
        echo "Installing AWS CLI..."
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip -qq awscliv2.zip
        sudo ./aws/install
        export AWS_EC2_METADATA_DISABLED=true
        aws --version

        echo "Downloading ConfD..."
        aws s3 cp --quiet --endpoint-url=${{ secrets.DO_SPACES_DEV_ENDPOINT }} s3://bin/confd-basic-8.0.10.linux.x86_64.zip confd.zip
        unzip confd.zip
    
    - name: Build Droplet Image
      env:
        DIGITALOCEAN_TOKEN: ${{ secrets.DO_TOKEN }}
      working-directory: packer
      run: |
        packer init .
        packer build digitalocean.pkr.hcl
