name: Packer Build

on:
  workflow_dispatch:  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup HashiCorp Packer
      uses: hashicorp/setup-packer@v2.0.1

    - name: Fetch Installers
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.DO_SPACES_DEV_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.DO_SPACES_DEV_ACCESS_KEY }}
      run: |
        export AWS_EC2_METADATA_DISABLED=true
        aws s3 cp --quiet --endpoint-url=${{ secrets.DO_SPACES_DEV_ENDPOINT }} s3://bin/confd-8.0.linux.x86_64.installer.bin confd-8.0.linux.x86_64.installer.bin
        aws s3 cp --quiet --endpoint-url=${{ secrets.DO_SPACES_DEV_ENDPOINT }} s3://bin/pt-topology-0.1.0.tgz pt-topology-0.1.0.tgz
        aws s3 cp --quiet --endpoint-url=${{ secrets.DO_SPACES_DEV_ENDPOINT }} s3://bin/yumapro-client-21.10-12.deb11.amd64.deb yumapro-client-21.10-12.deb11.amd64.deb
    
    - name: Build Droplet Image
      env:
        DIGITALOCEAN_TOKEN: ${{ secrets.DO_TOKEN }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      working-directory: packer
      run: |
        packer init .
        packer build yangcatalog.pkr.hcl -only '*.digitalocean.*'
