name: Packer Build

on:
  workflow_dispatch:  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup HashiCorp Packer
      uses: hashicorp/setup-packer@v2.0.1
    
    - name: Build Droplet Image
      env:
        DIGITALOCEAN_TOKEN: ${{ secrets.DO_TOKEN }}
      working-directory: packer
      run: |
        packer init .
        packer build digitalocean.pkr.hcl
